// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZN9uASrIk5ihwKRYVdsMtKNylkfNsWLk',
    appId: '1:223249616491:web:fa6d96bbf5443acd86eb2e',
    messagingSenderId: '223249616491',
    projectId: 'water-4c292',
    authDomain: 'water-4c292.firebaseapp.com',
    databaseURL: 'https://water-4c292-default-rtdb.firebaseio.com',
    storageBucket: 'water-4c292.appspot.com',
    measurementId: 'G-SM1M65TDZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_eTtVQ4AbLsYgj__GkGiErmlpIPlsQFM',
    appId: '1:223249616491:android:f78795603080a99586eb2e',
    messagingSenderId: '223249616491',
    projectId: 'water-4c292',
    databaseURL: 'https://water-4c292-default-rtdb.firebaseio.com',
    storageBucket: 'water-4c292.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd5nXKw-LsQlHBwnwclJsCRhfIUI1h9lw',
    appId: '1:223249616491:ios:b58145deaf70d47c86eb2e',
    messagingSenderId: '223249616491',
    projectId: 'water-4c292',
    databaseURL: 'https://water-4c292-default-rtdb.firebaseio.com',
    storageBucket: 'water-4c292.appspot.com',
    iosBundleId: 'com.example.waterTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd5nXKw-LsQlHBwnwclJsCRhfIUI1h9lw',
    appId: '1:223249616491:ios:6757c55dfdf5d9d586eb2e',
    messagingSenderId: '223249616491',
    projectId: 'water-4c292',
    databaseURL: 'https://water-4c292-default-rtdb.firebaseio.com',
    storageBucket: 'water-4c292.appspot.com',
    iosBundleId: 'com.example.waterTest.RunnerTests',
  );
}
